### ISSUE TITLE
Weak Session ID - Cookie Generator

### ISSUE THREAD

**Issue by marcogarzini** [ethicalhack3r/DVWA#167] opened 2017-07-20 09:42 UTC
Hi,
Im tampering with the value of dvwaSession, but is not taking into account when the code generates new values.

So pressing the generator button i have dvwaSession=4 and with Burp Suite (Also tried other programs) I send a request setting dvwaSession to 35 and the response value returns me a dvwaSession=5 instead of 36.

Why is happening? It generates de dvwaSession by the sessionID? It won't make sense the exercise !

Cheers,
Marco.

**Comment by digininja** [comment] 2017-07-20 09:45
The idea is for you to work out the pattern in the session values not to
interfere with them. Will be easy at this level but as you go up the levels
it gets harder.

**Comment by mike-bailey** [comment] 2017-07-26 02:37
Sounds resolved as it's working by design, closing.

**Closed by mike-bailey** 2017-07-26 02:37 UTC
